package com.servicelens.graph.domain;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link ClassNode}.
 *
 * <p>Verifies:</p>
 * <ul>
 *   <li>Field accessors and mutators generated by Lombok {@code @Data}.</li>
 *   <li>Correct population of the {@link NodeType} field for each Java type kind.</li>
 *   <li>Consistency between the legacy {@code isInterface} boolean flag and the
 *       canonical {@link NodeType} discriminator.</li>
 *   <li>Default collection fields ({@code annotations}, {@code methods}, etc.) are
 *       mutable and initialised as empty lists, not {@code null}.</li>
 *   <li>Relationship field setters (superClass, implementedInterfaces, dependencies).</li>
 * </ul>
 *
 * <p>No Spring context, Neo4j connection, or mocks are required — {@link ClassNode}
 * is a plain Lombok-annotated Java class.</p>
 */
@DisplayName("ClassNode")
class ClassNodeTest {

    // ─────────────────────────────────────────────────────────────────────
    // Basic field accessors
    // ─────────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Basic field accessors")
    class FieldAccessorTests {

        @Test
        @DisplayName("qualifiedName, simpleName and packageName round-trip via setters/getters")
        void identityFieldsRoundTrip() {
            ClassNode node = new ClassNode();
            node.setQualifiedName("com.example.payment.PaymentService");
            node.setSimpleName("PaymentService");
            node.setPackageName("com.example.payment");

            assertThat(node.getQualifiedName()).isEqualTo("com.example.payment.PaymentService");
            assertThat(node.getSimpleName()).isEqualTo("PaymentService");
            assertThat(node.getPackageName()).isEqualTo("com.example.payment");
        }

        @Test
        @DisplayName("serviceName and filePath round-trip via setters/getters")
        void serviceAndPathRoundTrip() {
            ClassNode node = new ClassNode();
            node.setServiceName("payment-service");
            node.setFilePath("/repo/src/PaymentService.java");

            assertThat(node.getServiceName()).isEqualTo("payment-service");
            assertThat(node.getFilePath()).isEqualTo("/repo/src/PaymentService.java");
        }

        @Test
        @DisplayName("isAbstract and isPublic flags default to false")
        void booleanFlagsDefaultFalse() {
            ClassNode node = new ClassNode();

            assertThat(node.isAbstract()).isFalse();
            assertThat(node.isPublic()).isFalse();
        }

        @Test
        @DisplayName("springStereotype and javadocSummary default to null")
        void stringFieldsDefaultNull() {
            ClassNode node = new ClassNode();

            assertThat(node.getSpringStereotype()).isNull();
            assertThat(node.getJavadocSummary()).isNull();
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // NodeType discriminator
    // ─────────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("NodeType discriminator")
    class NodeTypeTests {

        @Test
        @DisplayName("NodeType defaults to null before any setter call")
        void nodeTypeDefaultsToNull() {
            assertThat(new ClassNode().getNodeType()).isNull();
        }

        @Test
        @DisplayName("CLASS NodeType is correctly assigned and retrieved")
        void classNodeTypeAssigned() {
            ClassNode node = classNode("MyService", NodeType.CLASS);

            assertThat(node.getNodeType()).isEqualTo(NodeType.CLASS);
        }

        @Test
        @DisplayName("INTERFACE NodeType is correctly assigned and retrieved")
        void interfaceNodeTypeAssigned() {
            ClassNode node = classNode("Payable", NodeType.INTERFACE);

            assertThat(node.getNodeType()).isEqualTo(NodeType.INTERFACE);
            assertThat(node.isInterface()).isTrue();
        }

        @Test
        @DisplayName("ENUM NodeType is correctly assigned and retrieved")
        void enumNodeTypeAssigned() {
            ClassNode node = classNode("OrderStatus", NodeType.ENUM);

            assertThat(node.getNodeType()).isEqualTo(NodeType.ENUM);
        }

        @Test
        @DisplayName("RECORD NodeType is correctly assigned and retrieved")
        void recordNodeTypeAssigned() {
            ClassNode node = classNode("PaymentRequest", NodeType.RECORD);

            assertThat(node.getNodeType()).isEqualTo(NodeType.RECORD);
        }

        @Test
        @DisplayName("ANNOTATION_TYPE NodeType is correctly assigned and retrieved")
        void annotationTypeNodeTypeAssigned() {
            ClassNode node = classNode("AuditLog", NodeType.ANNOTATION_TYPE);

            assertThat(node.getNodeType()).isEqualTo(NodeType.ANNOTATION_TYPE);
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // isInterface / NodeType consistency
    // ─────────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("isInterface vs NodeType consistency")
    class IsInterfaceConsistencyTests {

        @Test
        @DisplayName("isInterface=true is consistent with NodeType.INTERFACE")
        void isInterfaceTrueConsistentWithNodeType() {
            ClassNode node = new ClassNode();
            node.setInterface(true);
            node.setNodeType(NodeType.INTERFACE);

            assertThat(node.isInterface()).isTrue();
            assertThat(node.getNodeType()).isEqualTo(NodeType.INTERFACE);
        }

        @Test
        @DisplayName("isInterface=false is consistent with NodeType.CLASS")
        void isInterfaceFalseConsistentWithNodeType() {
            ClassNode node = new ClassNode();
            node.setInterface(false);
            node.setNodeType(NodeType.CLASS);

            assertThat(node.isInterface()).isFalse();
            assertThat(node.getNodeType()).isEqualTo(NodeType.CLASS);
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Default collection fields
    // ─────────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Default collection fields")
    class CollectionFieldTests {

        @Test
        @DisplayName("annotations list is empty (not null) by default")
        void annotationsDefaultEmpty() {
            ClassNode node = new ClassNode();

            assertThat(node.getAnnotations()).isNotNull().isEmpty();
        }

        @Test
        @DisplayName("methods list is empty (not null) by default")
        void methodsDefaultEmpty() {
            ClassNode node = new ClassNode();

            assertThat(node.getMethods()).isNotNull().isEmpty();
        }

        @Test
        @DisplayName("implementedInterfaces list is empty (not null) by default")
        void implementedInterfacesDefaultEmpty() {
            ClassNode node = new ClassNode();

            assertThat(node.getImplementedInterfaces()).isNotNull().isEmpty();
        }

        @Test
        @DisplayName("dependencies list is empty (not null) by default")
        void dependenciesDefaultEmpty() {
            ClassNode node = new ClassNode();

            assertThat(node.getDependencies()).isNotNull().isEmpty();
        }

        @Test
        @DisplayName("annotations list is mutable — elements can be added")
        void annotationsListIsMutable() {
            ClassNode node = new ClassNode();
            node.getAnnotations().add("Service");

            assertThat(node.getAnnotations()).containsExactly("Service");
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Relationship fields
    // ─────────────────────────────────────────────────────────────────────

    @Nested
    @DisplayName("Relationship fields")
    class RelationshipFieldTests {

        @Test
        @DisplayName("superClass field defaults to null and can be assigned")
        void superClassFieldAssignable() {
            ClassNode parent = classNode("AbstractBase", NodeType.CLASS);
            ClassNode child  = classNode("ConcreteImpl", NodeType.CLASS);
            child.setSuperClass(parent);

            assertThat(child.getSuperClass()).isSameAs(parent);
        }

        @Test
        @DisplayName("implementedInterfaces can be set to a specific list")
        void implementedInterfacesAssignable() {
            ClassNode iface = classNode("Payable", NodeType.INTERFACE);
            ClassNode impl  = classNode("PaymentService", NodeType.CLASS);
            impl.setImplementedInterfaces(List.of(iface));

            assertThat(impl.getImplementedInterfaces()).containsExactly(iface);
        }

        @Test
        @DisplayName("dependencies list can be populated with collaborator nodes")
        void dependenciesAssignable() {
            ClassNode service = classNode("OrderService", NodeType.CLASS);
            ClassNode repo    = classNode("OrderRepository", NodeType.CLASS);
            service.getDependencies().add(repo);

            assertThat(service.getDependencies()).containsExactly(repo);
        }
    }

    // ── helpers ────────────────────────────────────────────────────────────

    /**
     * Build a minimal {@link ClassNode} with simple name, qualified name, and node type set.
     *
     * @param simpleName the short class name
     * @param nodeType   the canonical kind of Java type
     * @return a populated {@link ClassNode}
     */
    private static ClassNode classNode(String simpleName, NodeType nodeType) {
        ClassNode node = new ClassNode();
        node.setSimpleName(simpleName);
        node.setQualifiedName("com.example." + simpleName);
        node.setNodeType(nodeType);
        if (nodeType == NodeType.INTERFACE) {
            node.setInterface(true);
        }
        return node;
    }
}
